
package messervices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonServiceService", targetNamespace = "http://messervices/", wsdlLocation = "http://localhost:8088/services?wsdl")
public class MonServiceService
    extends Service
{

    private final static URL MONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MONSERVICESERVICE_EXCEPTION;
    private final static QName MONSERVICESERVICE_QNAME = new QName("http://messervices/", "MonServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONSERVICESERVICE_WSDL_LOCATION = url;
        MONSERVICESERVICE_EXCEPTION = e;
    }

    public MonServiceService() {
        super(__getWsdlLocation(), MONSERVICESERVICE_QNAME);
    }

    public MonServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONSERVICESERVICE_QNAME, features);
    }

    public MonServiceService(URL wsdlLocation) {
        super(wsdlLocation, MONSERVICESERVICE_QNAME);
    }

    public MonServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONSERVICESERVICE_QNAME, features);
    }

    public MonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MonService
     */
    @WebEndpoint(name = "MonServicePort")
    public MonService getMonServicePort() {
        return super.getPort(new QName("http://messervices/", "MonServicePort"), MonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonService
     */
    @WebEndpoint(name = "MonServicePort")
    public MonService getMonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://messervices/", "MonServicePort"), MonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONSERVICESERVICE_EXCEPTION!= null) {
            throw MONSERVICESERVICE_EXCEPTION;
        }
        return MONSERVICESERVICE_WSDL_LOCATION;
    }

}
